### ISSUE TITLE
Option to export as textures in JPEG format

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#124]
Currently, it appears that image export is [hardcoded to use PNG format](https://github.com/KhronosGroup/glTF-Blender-Exporter/blob/master/scripts/addons/io_scene_gltf2/gltf2_generate.py#L2030-L2051). It could be a nice enhancement to offer a choice of texture format, starting with PNG and JPEG, and later offering KHR_texture_compression.

The advantage for JPEG would be smaller filesize and faster transmission for WebGL-based applications.

Related:
- https://stackoverflow.com/questions/10777782/for-opengl-webgl-is-png-or-jpeg-the-most-suitable-file-format
- https://docs.blender.org/manual/en/dev/data_system/files/media/image_formats.html

**Comment by Absulit** [comment]
I think my only suggestion to this is that the output format could be bound to the Blender output, which is the panel located in the Render tab (Render > Output [dropdown to select image format]).

The con is that JPG and PNG are not the only formats available in that dropdown.

If that is not possible any other option is fine (like in the current export panel)

**Comment by emackey** [comment]
I'd really like a pass-thru option.  For example, the `DamagedHelmet` sample model came with some JPG images, already compressed.  Some time ago I edited the geometry in Blender to remove a seam and re-exported with the Blender extension to upgrade it from glTF 1.x to 2, but then I hand-edited the exported model to point back at the original JPG files rather than the exporter's PNG files.

For this particular case, really I didn't want the exporter producing PNG or its own JPG files, I wanted it to just reference the pre-existing JPG files, without round-tripping them through decode/re-encode.

**Comment by punkoffice** [comment]
This is a pretty big deal.  Currently this Blender glTF exporter is not suitable for making GLB files for Facebook due to Facebook's 3MB limit.  The PNGs fill blow-out that limit.  Yet this exporter is the one that's mentioned on the official Facebook 3D post doco

**Comment by donmccurdy** [comment]
Work in progress: https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/181

This allows JPEG export but doesn't have the pass-through option yet. Testing would be welcome, here's the ZIP:

[io_scene_gltf2.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1854303/io_scene_gltf2.zip)
