### ISSUE TITLE
Export causes a 'count' error

### ISSUE THREAD

**Issue by ETstudios** [KhronosGroup/glTF-Blender-Exporter#168]
I'm getting errors related to 'count', both in the glTF viewer and inside three.js, when I try loading a glTF model made in Blender exported with the glTF 2.0 exporter. Not sure if it's a bug or an incorrect setting when exporting.

.blend file I'm using is attached below:
[glTF Error.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1778055/glTF.Error.zip)

**Comment by donmccurdy** [comment]
@ETstudios thanks for the info! If you want to try the version in progress at #166, that should solve most of the issue here. Currently this exporter has no support for NLA tracks, and exports only the active action; that PR causes all actions associated with an object's NLA tracks to be exported. You'll have to "Push Down" each action into a strip, to get something like this:

<img width="705" alt="screen shot 2018-03-03 at 11 09 35 pm" src="https://user-images.githubusercontent.com/1848368/36943142-615197ec-1f38-11e8-8be3-7e120a72ff60.png">

With that you'll still see some errors, but they're minor and the model should appear correctly with three animations available:

<img width="773" alt="screen shot 2018-03-03 at 11 14 28 pm" src="https://user-images.githubusercontent.com/1848368/36943162-b909f24a-1f38-11e8-9599-c7a2093d7514.png">


Unfortunately the "Mimic Open / Close" strip will still not get exported. We haven't got a solution for exporting specific strips yet. You can either play each action sequentially in three.js, or try to bake that strip to an action (I think Blender has a way to do this...).

**Comment by ETstudios** [comment]
Happy to help, and thank you very much! It showed up in the viewer, using that PR, so that's pretty fantastic progress compared to nothing showing up at all, for me. As a bonus, it now appears just fine inside three.js, albeit in the demo without animations. 

On the downside, only one of the animations is showing up and working, with a name that doesn't exist in the .blend file, and only with an active action. When I export without an active animation and everything in the NLA strips as shown, it doesn't show up with any animations, but the model and textures do still appear. 

<img width="1208" alt="screen shot 2018-03-04 at 02 46 53" src="https://user-images.githubusercontent.com/37030536/36943367-5d5be00c-1f56-11e8-88ef-559d6b0b1dc2.png">

I'm getting some more errors than you, though, which might be the issue? Though these errors seem more like shader and file path issues than anything that would affect the animations, to me.

<img width="910" alt="screen shot 2018-03-04 at 02 43 24" src="https://user-images.githubusercontent.com/37030536/36943343-e192fb36-1f55-11e8-9044-54cfa32df77e.png">

**Comment by donmccurdy** [comment]
@ETstudios that sounds like the result I would expect from the current stable version of the exporter — have you installed the version of the exporter from #166? Attached here:

[io_scene_gltf2.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1778879/io_scene_gltf2.zip)

Will also need to restart Blender to pick up the new exporter.

The other errors are fine. `FILE_NOT_FOUND` warning is a bug in my viewer (https://github.com/donmccurdy/three-gltf-viewer/issues/73) and the `VALUE_NOT_IN_RANGE` error is very minor; we'll likely change the spec to allow that in the future (https://github.com/KhronosGroup/glTF/issues/1083). Neither should be affecting animation.

**Comment by ETstudios** [comment]
@donmccurdy I thought I had, but the linked .zip has it working, now! Thank you very much. I'll definitely be keeping an eye on how this develops. 

<img width="1212" alt="screen shot 2018-03-04 at 15 12 50" src="https://user-images.githubusercontent.com/37030536/36950063-bb3c686e-1fbe-11e8-9834-d52d8318fed3.png">

**Comment by donmccurdy** [comment]
Glad it's working! I should probably also add, if you do want to upload to Facebook or use this file somewhere that requires strict validation, you can fix the last error by giving your emmissive material a value `<= 1`.

**Comment by ETstudios** [comment]
Noted! Will definitely keep that in mind.
