### ISSUE TITLE
Exposure setting affects texture export.

### ISSUE THREAD

**Issue by ncoder** [KhronosGroup/glTF-Blender-Exporter#184]
Repro steps:
Got to Properties | Scene | Color Management,
Set exposure to something really high/low: like: -6
Export to .gltf

Actual:
Exported textures on disk are really dark.

Expected:
Relative brightness and color space settings of images are unchanged from source.

Looks like using "  blender_image.save_render" uses the scene exposure setting, as well as possibly other settings that will create arbitrarily incorrect output.

**Comment by donmccurdy** [comment]
Confirmed issue here, thanks!

**Comment by donmccurdy** [comment]
https://github.com/KhronosGroup/glTF-Blender-Exporter/pull/181 will fix this issue IF the image is kept in its original format. See details there. Unfortunately if a PNG is converted to JPG (e.g. because the alpha channel is unused) I don't see any way to convert without using the Scene object and its various settings.

**Comment by donmccurdy** [comment]
I think we've done what can be done at this point; as long as your textures are in a format glTF supports (currently JPG and PNG) they won't be baked, and render settings won't apply.
