### ISSUE TITLE
Materials linked to objects (and not to object's data) are not exported

### ISSUE THREAD

**Issue by atteneder** [KhronosGroup/glTF-Blender-Exporter#186]
In Blender's material tab you can choose wheter you link the material to the data (mesh) or the object.
The benefit (also for the glTF) is that you can instantiate the same mesh with different materials applied.
Tested with GLB export.

**Comment by emackey** [comment]
Lost several hours to this bug.  The Blender COLLADA importer had set a bunch of materials to "Object" instead of "Data", and none of those meshes are present in the output.

![blenderexporter_issue186](https://user-images.githubusercontent.com/1235080/41119976-3b16d036-6a62-11e8-863c-4f8c0a6f44ab.png)

I've done a little debugging here and hope to have a PR soon...
