### ISSUE TITLE
Same mesh repeated, Instancing support? 

### ISSUE THREAD

**Issue by gravi2** [KhronosGroup/glTF-Blender-Exporter#203]
I am trying to export a sample model that has few hundred spheres in a cube, as shown below:

<img width="1279" alt="screen shot 2018-04-27 at 10 03 57 pm" src="https://user-images.githubusercontent.com/1253458/39392310-56de7bda-4a68-11e8-9067-47f4a34f92fe.png">

When I export this model, it results in a GLB file in access of 100MB.  I was able to get it down to 1.5MB after running the GLB via the draco compression, which is great! 
But I wanted to check if this is something the [Instantiation from GLTF spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#instantiation) is supposed to handle and if I was doing something wrong in my model/export. 

Are there other recommended ways for handling such cases? 

I am attaching the sample blender model.

[spheres.blend.zip](https://github.com/KhronosGroup/glTF-Blender-Exporter/files/1957308/spheres.blend.zip)

**Comment by donmccurdy** [comment]
Although glTF does not have a precise concept of instanced geometry, it should probably be considered best practice to reuse the same accessors across meshes so that loaders can infer reasonable optimizations. This Blender exporter currently does not do that, so I will mark this issue as an Enhancement.

You may find [this Gist](https://gist.github.com/mattdesl/aea40285e2d73916b6b9101b36d84da8), the attached script, and the comment at the bottom to be useful. Supposedly the problem "seems to go away when you set an object to use a single mesh data" but I have not tested that.

Draco can reduce the transmission size, but the asset still decompresses to 100MB on the other side so properly deduplicating should improve runtime performance.

**Comment by gravi2** [comment]
@donmccurdy thanks for the response and the link. I will try it out and report back. On a related note, is there any support in exporter for particle systems?

**Comment by gravi2** [comment]
@donmccurdy I can confirm that using the comment at the bottom of the gist, helps reduce the size of the exported glb file. Thanks for the tip.

I am guessing we are leaving this enhancement open so that the exporter can handle this better.

**Comment by donmccurdy** [comment]
> I am guessing we are leaving this enhancement open so that the exporter can handle this better.

Yes, there may be more the exporter can do — I'm not sure. Leaving this open until we find out.

> On a related note, is there any support in exporter for particle systems?

The glTF format does not support particle systems, so they'd need to be converted to meshes. I don't think the exporter can currently do that automatically.

**Comment by donmccurdy** [comment]
This is fixed in the new importer/exporter (https://github.com/KhronosGroup/glTF-Blender-IO) – duplicating meshes (with Alt+G) will result in a single mesh instance being reused.
