### ISSUE TITLE
Where I can find the glTF Metallic Roughness node of Blender?

### ISSUE THREAD

**Issue by PowerArmor** [KhronosGroup/glTF-Blender-Exporter#228]
![1](https://user-images.githubusercontent.com/39609135/40528076-161bc7a4-6022-11e8-96af-6ed69fe87a80.png)
In the data of KhronosGroup/glTF-Blender-Exporter,
It's link the glTF Metallic Roughness node & glTF Specular Glossiness node,
but I can't find these nodes to link,
So...Can anyone help me?

**Comment by Vinc3r** [comment]
In your master scene, just use File > Link, and go to the gltf blend file you want, for example `C:\Users\USERNAME\Documents\GitHub\glTF-Blender-Exporter\pbr_node\glTF2_Principled.blend\Material\` or `C:\Users\AXEON\Documents\GitHub\glTF-Blender-Exporter\pbr_node\glTF2_Principled.blend\NodeTree\`, that's it.

Personnaly, I prefer link or append the material instead of the node group, more convenient to use.

**Comment by Vinc3r** [comment]
I think this issue can be closed isn'it?

**Comment by emackey** [comment]
Thanks @Vinc3r.
