### ISSUE TITLE
Detect and export double sided meshes

### ISSUE THREAD

**Issue by donmccurdy** [KhronosGroup/glTF-Blender-Exporter#230]
The exporter currently only exports `material.doubleSided` if it's set on the special glTF cycles nodes. We should also detect the *Double Sided* setting on a mesh, and apply that to the material as well.

![screen shot 2018-05-27 at 1 59 33 pm](https://user-images.githubusercontent.com/1848368/40590620-82e0bce2-61b6-11e8-971c-71662b0e47a2.png)

**Comment by emackey** [comment]
Worth noting that this "double sided" flag is specifically in regards to double-sided lighting, not backface culling.  glTF made the decision to have one flag for both, such that you always get double-sided lighting (when glTF's flag is true) or else backface culling (when glTF's doubleSided flag is false).

From https://github.com/KhronosGroup/glTF/pull/864#issuecomment-290422764:

![blenderdoublesided](https://cloud.githubusercontent.com/assets/1235080/24507845/9bf033ae-152f-11e7-964d-19ca052adbc4.png)

Still, we can't use Blender's backface culling flag here, since that's per-viewport and not per-anything-on-the-model.  So I guess the mesh's double-sided flag is the best place to get this.

**Comment by donmccurdy** [comment]
Marking duplicate of https://github.com/KhronosGroup/glTF-Blender-IO/issues/154.
