### ISSUE TITLE
Export (at least) names of custom cycles node materials

### ISSUE THREAD

**Issue by Gibbz** [KhronosGroup/glTF-Blender-Exporter#257]
Im using cycles in my scene for materials using nodes. As im using this in a game environment, all I really need is the material name.

To repeat:
So apply a blank/default node/cycles material with name (ie M-MaterialName) to a mesh.
Export as gltf. 
And there is no mention of the material name in the file.

**Comment by erikwoods** [comment]
Check this out: https://github.com/KhronosGroup/glTF-Blender-Exporter/tree/master/pbr_node

Blender can do way more than the glTF format can, at this time.

**Comment by donmccurdy** [comment]
glTF supports PBR and unlit materials, and not arbitrary Blender cycles node graphs, which can't be exported directly to any format I'm aware of.

I do think we should be able to preserve the material name, even if it reverts to a default grey material in the glTF file — it sounds like fixing that would be sufficient?

**Comment by erikwoods** [comment]
After seeing the response from @donmccurdy, I re-read the issue. You edited it after my response, for clarity, which explains a few things. I originally misunderstood your issue.

I bring this up because now I'm just curious. I've been learning about a-frame, webvr, and the glTF format for a few weeks, and I would like to know why you would want/need to have the name of the material exported? I think I know why, but I don't see it explicitly spelled out anywhere.

I want to learn and would appreciate any response!

PS, sorry if my first response frustrated you. I can see why it would be frustrating! I certainly feel like a dumbass.

**Comment by donmccurdy** [comment]
@erikwoods I think your response above is fine 🙂 — it's common enough that people want to create PBR models and don't realize they need to use the special PBR cycles nodes included with the exporter. The readme is the best reference for that situation as you said. We're also working to improve this by supporting Blender's Principled BSDF materials, so you don't need the custom nodes.

I assume the OP has created custom materials in an environment like Unity, with handwritten shaders or whatnot, and just needs the material names in order to match things up at import time. For A-Frame and WebVR this would be unusual, but it's still something you can try:

```js
var shaderMaterial = new THREE.ShaderMaterial({...});
el.addEventListener('model-loaded', (e) => {
  var model = el.getObject3D('mesh');
  mesh.traverse((node) => {
    if (node.isMesh && node.material.name === 'MyMaterial') node.material = shaderMaterial;
  });
});
```

**Comment by erikwoods** [comment]
@donmccurdy Now you've got me super curious about what is being done in unity with a-frame. I... Can only imagine. Time to research!

Thanks so much for your time and help. I'm actually struggling to understand how to make any material work with my model in a-frame right now. I've tried using the a-frame docs, webvr docs, etc. Tried to use the materials bundled with the Blender plugin, tried to use a-frame components and images for a texture... I can't get it to do much other than a basic diffuse shader, via Blender. It's fun learning how to get where I need to go to make what I want. I feel like I'm close to figuring it out. Could I PM you about it or something?

**Comment by erikwoods** [comment]
Cool, thanks. I don't mind it being public, I just didn't want to hijack this issue and make it my thing.

**Comment by Gibbz** [comment]
Yep, for game dev that is really all I need. The material name.

**Comment by donmccurdy** [comment]
Fixed in the new exporter (https://github.com/KhronosGroup/glTF-Blender-IO) - arbitrary Cycles nodes give unique (empty) materials with the correct names.
<img width="421" alt="Screen Shot 2019-03-21 at 9 30 29 AM" src="https://user-images.githubusercontent.com/1848368/54768245-061cdb00-4bbc-11e9-8ae0-e1da84df29ca.png">
