### ISSUE TITLE
Exporter ignore map scale

### ISSUE THREAD

**Issue by mshamaseen** [KhronosGroup/glTF-Blender-Exporter#285]
The map size in blender internal is ignored by the exporter.

![xbbgfb](https://user-images.githubusercontent.com/38951661/44279354-c1ae1300-a259-11e8-8ea6-16395bb9c910.JPG)

The real mesh look like:

![right_render](https://user-images.githubusercontent.com/38951661/44281103-58310300-a25f-11e8-86ce-d9ac4b966dfa.png)

Whereas the exported mesh look like:

![wrong_render](https://user-images.githubusercontent.com/38951661/44281122-6b43d300-a25f-11e8-8867-2f08b623b7c4.png)

**Comment by donmccurdy** [comment]
You'll need to scale up the UVs rather than scaling the texture map, as this exporter does not implement the 'KHR_texture_transform' glTF extension. https://github.com/KhronosGroup/glTF-Blender-IO (in development) does implement it. That project is a combination of this exporter with an importer, and will eventually replace this project, so I don't think we'll implement texture transforms separately here.
