### ISSUE TITLE
Automatically link/enable glTF material node group

### ISSUE THREAD

**Issue by UX3D-nopper** [KhronosGroup/glTF-Blender-Exporter#38]
As soon as the exporter is enabled, the material node groups should be linked and enabled as well.

Evaluate, if this can somehow be realized, as at a later point of time, the node group is integrated in Blender.

**Comment by emackey** [comment]
Huge +1 on this.

Some random concerns and/or food for thought:

* If the node is auto-linked from a particular path (such as the user's add-ons folder), will the end-user's blend file still be portable to other systems, other users with different paths?

* What happens if two users have different versions of the node group and try to share a blend file?  Will the blend file break if there have been modifications to only one user's node group?

I suspect we could avoid the above two by using Blender's "append" rather than "link", such that a copy of the node group is placed into the blend file instead of a reference to a file path on the user's machine.  But, if true, this would bloat (a little bit) the size of each blend file.

In the future (next year?) Blender will release v2.8 with the new "Eevee" rendering engine.  This engine introduces a Blender-native PBR node, with inputs very similar to the glTF node group, but directly connected to a realtime desktop PBR shader instead of the offline Cycles render nodes.  If the exporter could take inputs from Eevee's PBR node instead of the custom Cycles node group, this would enable realtime previews in Blender as well as alleviating the filesystem concerns above.  But, it remains to be seen how closely Eevee's PBR node will align with glTF file contents.

**Comment by UX3D-nopper** [comment]
We have the glTF 2.0 workgroup call in some minutes - but to make it short:

Our goal is to deeply integrate the glTF 2.0 exporter into Blender. In future, the export script should be pre-installed and in best case enabled by default (e.g. like COLLADA). Also, the current material node tree is an interim solution and should be sooner or later replaced with an internal glTF 2.0 metallic roughness (and specualr glossiness node) node.

I completely agree, that this has to be based on "Eevee". As this node has more features than the current glTF 2.0, we probably have to enhance glTF 2.x to this level as well.

We can discuss this later on, need to prepare for the meeting.

Thx a lot for the feedback. I/we have this in mind.
